[default]
extend-ignore-identifiers-re = [
    "*Ba*",  # ./docs/Usage/cli.md:414:123
]


[default.extend-identifiers]
OTPs = "OTPs"

[default.extend-words]
aks = "aks"  # azure-kubernetes-service
ons = "ons" # add-ons
